---
- name: Configure web servers
  hosts: webservers
  become: yes
  vars:
    app_name: myapp
    app_version: "1.2.3"
    app_port: 8080
    
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - nodejs
        - npm
      tags: [packages]
    
    - name: Create application directory
      file:
        path: "/opt/{{ app_name }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Deploy application
      unarchive:
        src: "{{ app_name }}-{{ app_version }}.tar.gz"
        dest: "/opt/{{ app_name }}"
        remote_src: yes
      notify: restart app
      
    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}
      notify: reload nginx
      
    - name: Enable site
      file:
        src: /etc/nginx/sites-available/{{ app_name }}
        dest: /etc/nginx/sites-enabled/{{ app_name }}
        state: link
      notify: reload nginx
  
  handlers:
    - name: restart app
      service:
        name: "{{ app_name }}"
        state: restarted
        
    - name: reload nginx
      service:
        name: nginx
        state: reloaded